import{a as S,S as M,i as l}from"./assets/vendor-frHSA4Lh.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();async function h(o,e){const s={key:"50422817-e50accda15a7155d4d1bff625",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15};try{return(await S.get("https://pixabay.com/api/",{params:s})).data}catch(n){throw console.error(n),n}}const m=document.querySelector(".loader"),g=document.querySelector(".gallery"),P=new M(".gallery a"),p=document.querySelector(".loadMoreBtn");function y(o){const e=o.map(({webformatURL:s,largeImageURL:n,tags:t,likes:r,views:a,comments:w,downloads:v})=>`<li class="photo-card">
    <a class="gallery-item" href="${n}">
    <img src="${s}" alt="${t}" loading="lazy"/>
    </a>
    <div class="info">
            <p class="info-item"><b>Likes</b><br>${r}</p>
            <p class="info-item"><b>Views</b><br>${a}</p>
            <p class="info-item"><b>Comments</b><br>${w}</p>
            <p class="info-item"><b>Downloads</b><br>${v}</p>

    </div>
    </li>`).join("");g.insertAdjacentHTML("beforeend",e),P.refresh()}function q(){g.innerHTML=""}function b(){m.classList.remove("hidden")}function d(){m.classList.add("hidden")}function B(){p.classList.remove("hidden")}function f(){p.classList.add("hidden")}const $=document.querySelector(".form"),O=document.querySelector(".loadMoreBtn");let i=0;const L=15;let c="",u=0;f();$.addEventListener("submit",async o=>{if(o.preventDefault(),c=o.target.elements["search-text"].value.trim(),!!c){i=1,q(),f(),b();try{const e=await h(c,i);if(u=e.totalHits,d(),e.hits.length===0){l.warning({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(e.hits);const s=Math.ceil(u/L);i<s&&B()}catch(e){console.error(e),d(),l.error({message:"Something went wrong. Please try again later.",position:"topRight"})}}});O.addEventListener("click",async o=>{i+=1,b();try{const e=await h(c,i);d(),y(e.hits),x();const s=Math.ceil(u/L);i>=s&&(l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),f())}catch(e){console.error(e),l.error({message:"Something went wrong while loading more images.",position:"topRight"})}});function x(){const o=document.querySelector(".gallery .photo-card");if(o){const{height:e}=o.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
